added text on why if and while is not in the syntax and corrected images
AAU-Dat/P8-supporting-schema-creation pull request #228
Opened 2024-05-14 13:07 UTC by sebastianbot6969

2024-05-15 09:16 UTC, CasperStaahl approved these changes

2024-05-15 09:16 UTC, CasperStaahl commented on report/src/sections/03-preliminaries.tex
> +\end{figure}
Måske burde vi vise den abstrakte syntax for instruktioner, og måske forklare konverteringen ved hjælp af figurende.

I figurende burde S være I. Og i if else statementet burde det være I_1 og I_2, if og else branchen burde være forskellige after all.

2024-05-15 09:16 UTC, CasperStaahl commented on report/src/sections/03-preliminaries.tex
> +\end{figure}
Måske burde man også vise at i base casen så bliver instruktionen bare placeret på kanten.

2024-05-15 09:16 UTC, CasperStaahl commented on report/src/sections/03-preliminaries.tex
> +\end{figure}
Se afsnit 2.2 i formal methods: An app....

2024-05-16 06:54 UTC, Daniel-Runge requested changes
Udover glossaries package, så er det rigtig nice. Hvis du fjerner den så approver jeg.

2024-05-16 06:54 UTC, Daniel-Runge commented on report/src/setup/preamble.tex
> +\usepackage{glossaries}
Remove line 22. We no longer use the glossaries package.

2024-05-16 06:54 UTC, Daniel-Runge commented on report/src/setup/preamble.tex
> +\makeglossaries
Rmove line 67. We no longer use the glossaries package.

2024-05-16 07:01 UTC, Daniel-Runge approved these changes

2024-05-16 07:01 UTC, merged