Termination
AAU-Dat/P8-supporting-schema-creation pull request #300
Opened 2024-05-22 13:09 UTC by Maltesius

2024-05-22 13:50 UTC, CasperStaahl requested changes

2024-05-22 13:50 UTC, CasperStaahl commented on report/src/sections/04-theory/06-termination.tex
> +Hence, to prove that our analysis terminates, we would need to show that $\abssem{I}$ always reaches a fixed point.
This is almost correct... our goal of the analysis is to find some fixed point of a function that is given by the constraint described in abstract interpretation in preliminaries, so we need to show that this function has a fixed point. 

This function however is monotone if the abstract semantics are monotone.

2024-05-22 13:50 UTC, CasperStaahl commented on report/src/sections/04-theory/06-termination.tex
> +So from \autoref{thm:kleene_finite}, we see that, in order for the analysis to reach a fixed point in a finite number of steps, $\mathcal{P}(\ab{\mathfrak{E}})$ has to be defined over a finite and co
The function I talked about above will be defined for tuples over the power set of abstract environments, the power set is a complete lattice and therefore the tuples defined over are also a complete lattice and the same for finiteness.

2024-05-23 11:21 UTC, CasperStaahl requested changes

2024-05-23 11:21 UTC, CasperStaahl commented on report/src/sections/01-introduction.tex
> +    \item and finally in \autoref{subsec:termination} we show that our analysis will terminate.\todo{Write this section/subsection}
Remove the todo.

2024-05-23 11:21 UTC, CasperStaahl commented on report/src/sections/04-theory/06-termination.tex
> +Our analysis takes base in the constraint function seen in \autoref{}\todo{Insert reference when function is made}.
Function should be made.

2024-05-23 11:21 UTC, CasperStaahl commented on report/src/sections/04-theory/06-termination.tex
> +As \autoref{} \todo{reference of function} is defined over the abstract semantics, we need to show that $\abssem{I}$ is monotone, in order for it to be monotone.
Fix ref.

2024-05-23 11:21 UTC, CasperStaahl commented on report/src/sections/04-theory/06-termination.tex
> +Now, looking at the type of \autoref{}\todo{function reference}, we see that it maps to the tuples over the powerset of abstract environments.
fix ref.

2024-05-23 11:21 UTC, CasperStaahl commented on report/src/sections/04-theory/06-termination.tex
> +So from \autoref{thm:kleene_finite}, we see that, in order for the analysis to reach a fixed point in a finite number of steps, $\bigtimes_{i = 1}^n \mathcal{P}(\ab{\mathfrak{E}})$ has to be defined
`has to be finite and complete` instead of `defined over...`

2024-05-23 11:21 UTC, CasperStaahl commented on report/src/sections/04-theory/06-termination.tex
> +Now, from \autoref{thm:absenv} we can conclude that the powerset $\mathcal{P}(\ab{\mathfrak{E}})$ is defined over a finite and complete lattice, and is therefore also a finite and complete lattice.
`is a finite...` instead of `defined over`.

2024-05-23 11:21 UTC, CasperStaahl commented on report/src/sections/04-theory/06-termination.tex
> +Following this, it also holds that the $\bigtimes_{i = 1}^n \mathcal{P}(\ab{\mathfrak{E}})$ must be a finite and complete lattice for the same reason as $\mathcal{P}(\ab{\mathfrak{E}})$.
Mention the relevant theorems for preliminaries.

2024-05-23 11:21 UTC, CasperStaahl commented on report/src/sections/aa-appendix/05-termination.tex
> +    \step{application}{$\ab{\mathfrak{E}}_a$ is a finite and complete lattice}
We actually only have to show that it is finite.

2024-05-23 11:21 UTC, CasperStaahl commented on report/src/sections/aa-appendix/05-termination.tex
> +        Therefore, the union must also be a finite and complete lattice.
just mention that they are finite we don't really care about the lattice part.

2024-05-23 11:21 UTC, CasperStaahl commented on report/src/sections/aa-appendix/05-termination.tex
> +    \step{database}{$\ab{\mathfrak{E}}_d$ is a finite and complete lattice}
Same as above.

2024-05-23 11:21 UTC, CasperStaahl commented on report/src/sections/aa-appendix/05-termination.tex
> +        Again, this means that from \autoref{co:topcoverr} and~\ref{co:topcoveri}, we know that the cover lattices are all finite and complete lattices.
Again we only care about the finite part.

2024-05-23 11:21 UTC, CasperStaahl commented on report/src/sections/aa-appendix/05-termination.tex
> +        For the same reason, the union between all database variables must also be a finite and complete lattice.
again just remove all mentions of lattices...

2024-05-23 11:21 UTC, CasperStaahl commented on report/src/sections/04-theory/06-termination.tex
> +\end{restatable}
We only care about it being finite. This should also be reflected in the proof.

2024-05-23 14:15 UTC, CasperStaahl approved these changes

2024-05-23 14:22 UTC, sebastianbot6969 approved these changes

2024-05-23 14:23 UTC, merged